export { getPeopleOptions } from './api/get-people-list';
export { getPersonOptions } from './api/get-person';
export { getDirectOptions } from './api/get-direct';
export { PersonCard } from './ui/card';
export { PendingText } from './ui/pending-text';
export { AdditionalBlock } from './ui/additional-block';
export { MainInfo } from './ui/main-info';
export { useIsShowPendingText } from './hooks/use-is-show-pending-text';
export { useRewriteStore, useGetMergedPerson } from './model/rewrite-store';
export * from './types';
