name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci --include=optional
        env:
          NPM_CONFIG_OPTIONAL: 'true'
          NODE_ENV: development

      - run: corepack enable
      - run: corepack prepare pnpm@9 --activate
      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: SPA 404 fallback
        run: |
          if [ -d dist ]; then cp dist/index.html dist/404.html; fi
          if [ -d build ]; then cp build/index.html build/404.html; fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            dist
            build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
